apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
data:
  enable-opentracing: "true"
  # see log fields for available variables
  opentracing-operation-name: "$request_method $host"
  # opentracing-location-operation-name: "$proxy_upstream_name"
  # opentracing-location-operation-name: "$ingress_name"
  opentracing-location-operation-name: "$namespace $service_name"
  jaeger-collector-host: jaeger.jaeger.svc.cluster.local
  # endpoint was committed after 0.44.0, so available in 0.45.0 (probably)
  # jaeger-endpoint: "http://jaeger.jaeger.svc.cluster.local:14268/api/traces"
  jaeger-service-name: nginx-default
  jaeger-sampler-type: ratelimiting
  jaeger-sampler-param: "5"
