apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: ingress-nginx
resources:
  - clusterrole.k8s.yaml
  - clusterrolebinding.k8s.yaml
  - configmap.k8s.yaml
  - deployment.k8s.yaml
  - job.k8s.yaml
  - namespace.k8s.yaml
  - role.k8s.yaml
  - rolebinding.k8s.yaml
  - service.k8s.yaml
  - serviceaccount.k8s.yaml
  - validatingwebhookconfiguration.k8s.yaml
