apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaeger
commonLabels:
  app.kubernetes.io/name: jaeger
resources:
  - namespace.k8s.yaml
  - deployment.k8s.yaml
  - ingress.k8s.yaml
  - service.k8s.yaml
